name: file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
          fi

      - name: Crear Pull Request
        id: create_pr
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ env.OWNER }}/${{ env.REPO }}/pulls
          token: ${{ secrets.REPO_TOKEN }}
          title: Automated Pull Request
          head: develop
          base: main
          body: |
            This pull request was automatically created upon pushing changes to the repository.
            
        # uses: reviewdog/action-github-pr-review@v1
        # with:
        #   github_token: ${{ secrets.REPO_TOKEN }}
        #   level: info
        #   tool_name: assign-reviewer
        #   check_name: Assign Reviewer
        #   reviewdog_flags: -assign "Maik2805"
      - name: Get repository collaborators
        id: collaborators
        run: |
          collaborators=$(gh api repos/:owner/:repo/collaborators -q '.[].login')
          echo "::set-output name=collaborators::$collaborators"

      - name: Select random reviewer
        id: random_reviewer
        run: |
          collaborators=($(echo "${{ steps.collaborators.outputs.collaborators }}" | tr -d '"'))
          random_index=$((RANDOM % ${#collaborators[@]}))
          random_reviewer=${collaborators[$random_index]}
          echo "::set-output name=random_reviewer::$random_reviewer"

      - name: Assign Random Reviewer
        uses: actions/review-assign-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ steps.random_reviewer.outputs.random_reviewer }}