name: file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
          fi

      - name: Install GitHub CLI (if not already installed)
        run: |
          if ! which gh >/dev/null 2>&1; then
            sudo apt update && sudo apt install -y curl gnupg2
            curl -sSL https://cli.github.com/packages/scripts/ubuntu-jammy.sh | sudo bash -s -
          fi

      - name: Create Pull Request
        run: |
          # Obtain the name of the branch
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Create the Pull Request
          gh pr create --title "Automated PR from $BRANCH" --base main

      - name: Get Collaborators
        run: |
          COLLABORATORS=$(gh api repos/${{ github.repository }}/collaborators | jq -r '.[].login')

      - name: Select Random Reviewers
        run: |
          # Select two random reviewers from the list of collaborators
          REVIEWERS=($(shuf -e $COLLABORATORS | head -n 2))

      - name: Assign Reviewers
        run: |
          PR_NUMBER=$(gh pr list | head -n 1 | awk '{print $1}')
          for reviewer in "${REVIEWERS[@]}"; do
            gh pr review-request create --reviewer $reviewer --requestee ${{ github.actor }} --repo ${{ github.repository }} --number $PR_NUMBER
          done

      - name: Post Checkout repo
        run: echo "Checkout completed successfully"

      - name: Post Setup python
        run: echo "Python setup completed successfully"

      - name: Complete job
        run: echo "Job completed successfully"
