name: file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
          fi

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     commit-message: update cgchange
      #     title: auto hcange
      #     body: Update changelog to reflect release changes
      #     branch: main
      #     base: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update changes
          title: Automatically create pull request
          body: This pull request was automatically created.
          branch: develop
          base: main
          token: ${{ secrets.REPO_TOKEN }


      # - name: Asignar Revisor
      #   run: |
      #     pr_number=$(cat $GITHUB_EVENT_PATH | jq -r '.number')
      #     curl -X POST \
      #       -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -d '{"reviewers":["Maik2805"]}' \
      #       "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/requested_reviewers"