name: file

on: 
  push:
    branches:
      '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            exit 1
          fi

      - name: Create Pull Request and Assign Reviewers
        run: |
          # Obtener el nombre de la rama
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Crear el Pull Request
          gh pr create --title "Automated PR from $BRANCH" --base main
          
          # Obtener una lista de colaboradores
          COLLABORATORS=$(gh api repos/${{ github.repository }}/collaborators | jq -r '.[].login')
          
          # Seleccionar dos revisores aleatorios de la lista de colaboradores
          REVIEWERS=($(shuf -e $COLLABORATORS | head -n 2))
          
          # Asignar los revisores al PR
          PR_NUMBER=$(gh pr list | head -n 1 | awk '{print $1}')
          for reviewer in "${REVIEWERS[@]}"; do
            gh pr review-request create --reviewer $reviewer --requestee ${{ github.actor }} --repo ${{ github.repository }} --number $PR_NUMBER
          done