name: file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      PR_NUMBER: ''
      

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
          fi

      - name: create pull request
        run: 
          pr_number=$(gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by GitHub Actions' | grep -oP '(?<=#)\d+')
          echo "::set-output name=pr_number::$pr_number"
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Asignar Revisor
        run: |
          pr_number=$PR_NUMBER
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"reviewers":["Maik2805"]}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/requested_reviewers"