name: file

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      PR_NUMBER: ''
      GH_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install || exit 1

      - name: Build front-end
        run: |
          npm run build || exit 1
        
      - name: Assign Random Reviewer
        run: |
          latest_pr_number=$(gh pr list | head -n 1 | awk '{print $1}')
          echo "EL ULTIMO PR ES: $latest_pr_number"
          output=$(gh api repos/ccgg1997/CLASEDS2/collaborators | jq -r '.[].login')
          read -r -a collaborators <<< "$output"
          random_index=$(( RANDOM % ${#collaborators[@]} ))
          random_reviewer=${collaborators[random_index]}
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"reviewers\":[\"$random_reviewer\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${latest_pr_number}/requested_reviewers"

  close-pr:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull-request@v2
        with:
          message: "Automatic PR close due to build failure."
          comment: "The pull request was automatically closed because the build failed."
          labels: "automatically-closed"
          repo-token: ${{ secrets.REPO_TOKEN }}
