name: file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate file creation
        run: |
          python ./example.py
          if [ -f "file.txt" ]; then
            echo "file.txt exists"
          else
            echo "file.txt does not exist"
            echo "**Validation failed. Skipping PR creation and reviewer assignment.**"
            exit 1  # Use a non-zero exit code to indicate failure, but don't prevent the push
          fi

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: "Automatically created pull request"
      #     title: "Automated Pull Request"
      #     body: "This pull request was automatically created upon pushing changes to the repository."
      #     branch: main
      #     base: develop
      - name: Create Pull Request
        uses: actions/github-script@v6  # Use v6 for better compatibility
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const { owner, repo } = context.repo;  # Correctly access context
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            try {
              const pullRequest = await octokit.rest.pulls.create({
                owner,
                repo,
                title: "Automated Pull Request",
                body: "This pull request was automatically created upon pushing changes to the repository.",
                head: "develop",
                base: "main"
              });
              console.log(`Pull request created: ${pullRequest.data.html_url}`);
            } catch (error) {
              console.error('Error creating pull request:', error);
              // Add more robust error handling if needed
            }

      -  name: Add Automatic Pull Request Reviewers
         uses: buzato/add-reviewer-gh-action@1.0.5
         with: 
          reviewers: "Maik2805"
          token: ${{ secrets.GITHUB_TOKEN }}
